### ISSUE TITLE
Points conversion rate does not refresh for each record displayed.

### ISSUE THREAD

**Issue by jsibala** [ghelobytes/autohub#4]
Every time a transaction is processed, the points conversion rate should refresh depending on the membership type (elite 1:20, platinum elite 1:15) of the current record being processed.
Right now its remains at 1:15 even if the member is elite.

**Comment by ghelobytes** [comment]
@jsibala sir please provide me a test case like login (username/password) to use, specific member to process, and other pertinent details

**Comment by jsibala** [comment]
login as C1ACCS pw: cashier
load and process transaction: Member1 that should be Elite so 1:20 conversion rate
load and process transaction: Member2 or Member3, they are Platinum Elite so 1:15 conversion rate.

**Comment by ghelobytes** [comment]
@jsibala sir please confirm if this is fixed

**Comment by jsibala** [comment]
I have tested and this is fixed.  Thank you.
